### ISSUE TITLE
Cannot make it work

### ISSUE THREAD

**Issue by spaceknight** [code-fi/ionic3-radio-app#2]
Hello,

I try to make the app work with no luck.

This is what I am doing:

ionic start ionic3-radio blank

cd ionic3-radio

git clone https://github.com/code-fi/ionic3-radio-app.git

ionic cordova platform add android

ionic cordova platform add browser

ionic cordova plugin add cordova-plugin-media

ionic cordova prepare --prod

This is the error I get after executing last line in Terminal:

[WARN] Cannot perform Ionic build without platform. Falling back to just cordova prepare.
       
       Please supply a platform (e.g. android, ios) so the Ionic CLI can build web assets. The --no-build
       option will hide this warning.

When I type: npm run ionic:serve

I get 
npm ERR! missing script: ionic:serve

When I type ionic serve

The app runs but I get the default blank ionic app in the browser.

Is there something wrong with the paths or app names in the readme?

Thanks,

**Comment by code-fi** [comment]
follow the new readme

i have updated the repo to the latest ionic
